//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Acme.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAcmeListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AcmeBaseListener : IAcmeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.pseudoOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPseudoOps([NotNull] AcmeParser.PseudoOpsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.pseudoOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPseudoOps([NotNull] AcmeParser.PseudoOpsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.expressionPseudoOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionPseudoOps([NotNull] AcmeParser.ExpressionPseudoOpsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.expressionPseudoOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionPseudoOps([NotNull] AcmeParser.ExpressionPseudoOpsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.hexByteValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexByteValues([NotNull] AcmeParser.HexByteValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.hexByteValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexByteValues([NotNull] AcmeParser.HexByteValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.fillValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFillValues([NotNull] AcmeParser.FillValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.fillValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFillValues([NotNull] AcmeParser.FillValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.skipValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkipValues([NotNull] AcmeParser.SkipValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.skipValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkipValues([NotNull] AcmeParser.SkipValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.alignValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlignValues([NotNull] AcmeParser.AlignValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.alignValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlignValues([NotNull] AcmeParser.AlignValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.convtab"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConvtab([NotNull] AcmeParser.ConvtabContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.convtab"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConvtab([NotNull] AcmeParser.ConvtabContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.stringValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringValues([NotNull] AcmeParser.StringValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.stringValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringValues([NotNull] AcmeParser.StringValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.scrxor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScrxor([NotNull] AcmeParser.ScrxorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.scrxor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScrxor([NotNull] AcmeParser.ScrxorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.to"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTo([NotNull] AcmeParser.ToContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.to"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTo([NotNull] AcmeParser.ToContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.source"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSource([NotNull] AcmeParser.SourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.source"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSource([NotNull] AcmeParser.SourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary([NotNull] AcmeParser.BinaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.binary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary([NotNull] AcmeParser.BinaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.zone"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterZone([NotNull] AcmeParser.ZoneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.zone"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitZone([NotNull] AcmeParser.ZoneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.symbollist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbollist([NotNull] AcmeParser.SymbollistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.symbollist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbollist([NotNull] AcmeParser.SymbollistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.flowOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlowOps([NotNull] AcmeParser.FlowOpsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.flowOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlowOps([NotNull] AcmeParser.FlowOpsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.ifFlow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfFlow([NotNull] AcmeParser.IfFlowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.ifFlow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfFlow([NotNull] AcmeParser.IfFlowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.ifDefFlow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfDefFlow([NotNull] AcmeParser.IfDefFlowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.ifDefFlow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfDefFlow([NotNull] AcmeParser.IfDefFlowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.forFlow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForFlow([NotNull] AcmeParser.ForFlowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.forFlow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForFlow([NotNull] AcmeParser.ForFlowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.expressionPseudoCodes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionPseudoCodes([NotNull] AcmeParser.ExpressionPseudoCodesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.expressionPseudoCodes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionPseudoCodes([NotNull] AcmeParser.ExpressionPseudoCodesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] AcmeParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] AcmeParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] AcmeParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] AcmeParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.filename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilename([NotNull] AcmeParser.FilenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.filename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilename([NotNull] AcmeParser.FilenameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] AcmeParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] AcmeParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] AcmeParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] AcmeParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] AcmeParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] AcmeParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.decNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecNumber([NotNull] AcmeParser.DecNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.decNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecNumber([NotNull] AcmeParser.DecNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.hexNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHexNumber([NotNull] AcmeParser.HexNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.hexNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHexNumber([NotNull] AcmeParser.HexNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.binNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinNumber([NotNull] AcmeParser.BinNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.binNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinNumber([NotNull] AcmeParser.BinNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.logicalop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalop([NotNull] AcmeParser.LogicalopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.logicalop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalop([NotNull] AcmeParser.LogicalopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbol([NotNull] AcmeParser.SymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbol([NotNull] AcmeParser.SymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.binaryop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryop([NotNull] AcmeParser.BinaryopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.binaryop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryop([NotNull] AcmeParser.BinaryopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AcmeParser.opcode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpcode([NotNull] AcmeParser.OpcodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AcmeParser.opcode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpcode([NotNull] AcmeParser.OpcodeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
